### ISSUE TITLE
Localizing

### ISSUE THREAD

**Issue by CryssDOTnet** [nasendackel/yellow-comments#1]
How can I start to translate it? I don't know anything about php. How hard is it to add the feature of language files like in the other plugins?

Regards,
Chris

**Comment by ghost** [comment]
This is just the stuff, I put quickly put together for my own blog. 
I hope, that someone uses it to create a proper yellow extension. Then there will be no problem with languages.

Aber es sollte in Deutsch funktionieren.

**Comment by wunderfeyd** [comment]
I'll try to investigate into this (and the whole plugin) at the weekend. Was too busy doing other things since the request for the upload to GitHub.

**Comment by ghost** [comment]
The Plugin nie supports language files and currently supports English and German.

**Comment by ghost** [comment]
I meant NOW supports language files.
