### ISSUE TITLE
Set last modified time for current page

### ISSUE THREAD

**Issue by wunderfeyd** [nasendackel/yellow-comments#10]
Set last modified time for current page, otherwise the comments aren't updated by a browser refresh sometimes.

**Comment by ghost** [comment]
Thanks for the hint :+1:

**Comment by wunderfeyd** [comment]
I'm going to add this with the next development iteration. But my spare time is rare at the moment. :\

**Comment by ghost** [comment]
Take your time.  :)

**Comment by wunderfeyd** [comment]
Should work with commit https://github.com/nasendackel/yellow-comments/commit/8d50aed62ac7ae3cd8a493ea26e380f2ede8826c.
