### ISSUE TITLE
seek warning in latest version

### ISSUE THREAD

**Issue by ghost** [nasendackel/yellow-comments#11]
> Warning: fseek() expects parameter 1 to be resource, null given in comments.php on line 167
> Warning: ftell() expects parameter 1 to be resource, null given in comments.php on line 168
> Warning: fseek() expects parameter 1 to be resource, null given in comments.php on line 169
> Warning: fread() expects parameter 1 to be resource, null given in comments.php on line 170

No Idea what this means, but I get this error.

**Comment by ghost** [comment]
Sorry, that was my mistake. But I still have this error with posts with 0 Comments:

> Warning: fread() [function.fread]: Length parameter must be greater than 0 in comments.php on line 170

**Comment by wunderfeyd** [comment]
Thank you for your bug report. I'll check this tomorrow. It's interesting the [PHP documentation](https://secure.php.net/manual/en/function.fread.php) doesn't cover this. Although a read of zero bytes is not needed (which this warning is trying to state I assume) it doesn't make sense in the end. :)

**Comment by wunderfeyd** [comment]
@nasendackel: Could you test the latest version please.

**Comment by ghost** [comment]
Works fine! Thanks!

**Comment by wunderfeyd** [comment]
Thanks for your good and exact feedback/report. :+1:
