### ISSUE TITLE
How to edit a comment...

### ISSUE THREAD

**Issue by ghost** [nasendackel/yellow-comments#12]
Hi, maybe I am stupid, but how can I edit a comment via the web-interface?

**Comment by wunderfeyd** [comment]
Depends on your `commentsDir` settings.

If it's not set, go to `http://<website>/<blog-entry>-comments` and click on "Edit page". (Where `-comments` is your `commentsExtension`)

If it's set and the location is inside the `content` directory, just adapt your browsing url respectively.

If it's set and it's outside the `content` directory, you can't edit your files with the web interface. You have to use your ftp client and/or favorite editor to modify the comments.

---

But you are right. For easier access we should add a link at the bottom when editing the blog page (at least for the two first options). This can be achived by modifing the `content-blog.php` file.

What do you think?

**Comment by ghost** [comment]
Ah, my comments are still outside the content folder. Time to change it.

**Comment by ghost** [comment]
And a link a the bottom would be helpful...

**Comment by wunderfeyd** [comment]
Yup, I'll update the code the next days. Also a comment page shouldn't be accessible from outside the edit mode. This will be fixed too.

**Comment by wunderfeyd** [comment]
Added link to edit page. Comments pages aren't longer accessible to the user (the page itself was valid no comments were seen). Thanks to @markseu for the hint to the `available` property.

@nasendackel: Could you test the latest commit please?

**Comment by ghost** [comment]
@wunderfeyd I will test it tonight :+1:

**Comment by ghost** [comment]
Seems to work! 👍

**Comment by wunderfeyd** [comment]
Great! Thank you! 

Let me know if you need something else.
