### ISSUE TITLE
Exclude -comments textiles form search

### ISSUE THREAD

**Issue by ghost** [nasendackel/yellow-comments#13]
There is the problem, that the comments file are been found by the search. Is there a way to exclude them?

For an example look at this:
[http://www.nasendackel.de/search/query:sublimetext/](http://www.nasendackel.de/search/query:sublimetext/)

**Comment by wunderfeyd** [comment]
Thanks for pointing me at this. I already set the page as invisible but it looks like it's not done correctly in all circumstances. I'll update the code the next days.

**Comment by markseuffert** [comment]
You can add `Status: hidden` to the settings at the top of a page. This might work with comments too.

**Comment by ghost** [comment]
Sorry, my fault. I just saw that everything is alright. I just had some empty comment files from the very early days of this plugin. :) :+1:

**Comment by wunderfeyd** [comment]
@markseu: Thanks will add this to the default comment page template.
@nasendackel: Great! Nevertheless I'll check the code twice. Comments shouldn't show up anywhere except in edit mode and on the commented page.

**Comment by wunderfeyd** [comment]
Rechecked. All is fine here.
