### ISSUE TITLE
Use shared content folder for new comment template

### ISSUE THREAD

**Issue by schulle4u** [nasendackel/yellow-comments#20]
In the upcoming 0.8.1 Yellow release, content templates such as `page-new-*.md` are stored in a new shared content folder (`/content/shared` by default). The Yellow updater moves all these files from the config folder to the new location, which partially breaks the comments template. Re-uploading `page-new-comments.md` to the config folder solves this. 
I suggest to make use of the new shared content folder. 

Steffen

**Comment by GiovanniSalmeri** [comment]
Thank you very much for the hint, I will try to fix the plugin in the next days.

**Comment by GiovanniSalmeri** [comment]
I have just commited the new version. Actually I realised that the template was a leftover from the previous version, but was not used. So one file less!
