### ISSUE TITLE
 Comments: 0  Comments are closed.

### ISSUE THREAD

**Issue by flagsoft** [nasendackel/yellow-comments#21]
Can't make this work, using Yellow 0.7.x:
Alawys getting:

Comments: 0

Comments are closed.

What's missing?

If want to use it within
system/themes/templates/default.html

But I can only use:
```<?php echo $yellow->page->getExtra("comments") ?>```

How can I give comments an argument like [comments 0]?

If I use [comments 0] the form is displayed but only on that page, and nothing happens, commenting is not possible, does not work.

**Comment by wunderfeyd** [comment]
Which Yellow version do you use exactly?

**Comment by GiovanniSalmeri** [comment]
I will check as soon as possible the plugin with the latest version of Yellow, sorry for not being very present in the latest months.

**Comment by GiovanniSalmeri** [comment]
> How can I give comments an argument like [comments 0]?

You have to set the variable `commentsOpening` in system.ini. Please remark that if you set a number of days (the default is 30) this number is relative to the *publication* date of the page. If there is no publication date, then you can use only the settings 0 and 1. For example, in the sample pages of the Blog plugin/extension, comments are closed unless you set a number of days greater than the difference between the current date and their publication date. I am just in the process of updating the extension to the new API, but nothing will change in this regard.

**Comment by GiovanniSalmeri** [comment]
I close this issue, since #22 is very similar.
