### ISSUE TITLE
Comments disappear after being published

### ISSUE THREAD

**Issue by Ordresser** [nasendackel/yellow-comments#24]
I get an email and with the email link publish a comment, which takes me to the page with the comment published. Great.

But when I go to that page on my blog again, there is no comment there, just the 'submit a comment' form.

**Comment by GiovanniSalmeri** [comment]
@Ordresser Thank you for the report, I will look into it as soon as possible

**Comment by foxnoodles** [comment]
Same here. Comments don't get published nor stored.
