### ISSUE TITLE
language text file issue

### ISSUE THREAD

**Issue by KeerlITServices** [nasendackel/yellow-comments#28]
Hiya,
I just downloaded the zip file into my extensions folder and restarted apache (by habit).
The form does show up, but the correct labels are missing.
"[commentsComments] : 0"
was shown, instead of Kommentare: 0

By the looks of it, the file comments.txt was missing, which I plainly copied over from the zip file.

Cheers
JK

**Comment by GiovanniSalmeri** [comment]
Thank you very much for noticing! I have corrected extension.ini here and in my other extensions.
