### ISSUE TITLE
foreach() argument must be of type array|object

### ISSUE THREAD

**Issue by gorth-git** [nasendackel/yellow-comments#30]
Hello,
with PHP 8.1 there is an error in th PHP script:
```
Warning: foreach() argument must be of type array|object, null given in /var/www/html/system/extensions/comments.php on line 314
Warning: foreach() argument must be of type array|object, null given in /var/www/html/system/extensions/comments.php on line 50
```
In each of the lines you can prevent this warning with
`foreach ($this->comments ?? [] as $comment)`

Best regards
  Guenther

**Comment by GiovanniSalmeri** [comment]
Fixed with https://github.com/GiovanniSalmeri/yellow-comments/commit/c2694be0da2620b8657f65799e38e8c2ad5ddaa7. Thank you very much!
