### ISSUE TITLE
FILTER_SANITIZE_STRING is deprecated in PHP 8.1

### ISSUE THREAD

**Issue by gorth-git** [nasendackel/yellow-comments#31]
In line 197 and 198 there is a filter FILTER_STANITIZE_STRING. In PHP 8.1, this filter is deprecated.
You can replace this filter with FILTER_UNSAFE_RAW for a quick fix.

**Comment by GiovanniSalmeri** [comment]
Fixed with https://github.com/GiovanniSalmeri/yellow-comments/commit/c2694be0da2620b8657f65799e38e8c2ad5ddaa7. Thank you very much!
