### ISSUE TITLE
Rename page setting

### ISSUE THREAD

**Issue by markseuffert** [nasendackel/yellow-comments#33]
`Comments: no` should be changed to `Comment: exclude` and the README should be updated after that. Reason is the naming convention for extensions and settings, a key is typically singular, a value for exclusion is typically `exclude`. For a similar use case see [command extension](https://github.com/annaesvensson/yellow-command).

**Comment by GiovanniSalmeri** [comment]
Regarding the value `exclude`: right, I will change it.

Regarding the key `Comment`, just a little doubt: in my intention, `Comments` is not a plural per se, but simply the name of the extension. So for example I would find it more natural and easy to remember if also in `yellow-disqus` the setting were named `Disqus` instead of `Comment`.

But if `Comment` fits better in the conventions of Yellow, I will change it 😊

**Comment by markseuffert** [comment]
Perhaps change  the name of the extension and the setting to `Comment`?  

It makes life easier to stick to singular. You don't have to think every time, what was the name again, should I put a letter 's' at the end this time? I see inconsistency as one of the biggest contributor to development waste. It occupies time to understand how different parts of a system fit together, even more time if they need to be changed in order to work well together. Let's take for example something common like `Title` and `Tag`. The title of a page can only be singular, here it's easy. The tag(s) on a page can be singular and plural. What should you do when you first have one tag and add another one, do you change your setting from `Tag` to `Tags`? Perhaps your preference/opinion would change in another context, but in order for extensions to work together, we need one agreed name. It makes life easier for developers. This is were the naming convention originated from.

**Comment by GiovanniSalmeri** [comment]
> Perhaps change the name of the extension and the setting to Comment?

Good idea, I will do that!

**Comment by GiovanniSalmeri** [comment]
Done with https://github.com/GiovanniSalmeri/yellow-comment/commit/c6baebeb82ada1b2a1fe5c21095c197689ae0b37. Thank you again!

**Comment by markseuffert** [comment]
Thank you. Then the [blog layout](https://github.com/annaesvensson/yellow-blog/blob/main/blog.html) should be changed too, change `getExtra()` arguments to singular to match?

**Comment by markseuffert** [comment]
Also done, extensions should be working together again.

**Comment by GiovanniSalmeri** [comment]
Perfect, thank you very much!
