### ISSUE TITLE
Comment showing under main Blog page

### ISSUE THREAD

**Issue by ghost** [nasendackel/yellow-comments#37]
Hi. Thank you for the Comment addon. 
I have an issue with comments showing in the main Blog page. Comment fields shows simply under blog post headlines. 
I've tried to add `Comment: exclude` in the main Blog page, but it still shows comment field. 
What do I do wrong? 
Thank you.

**Comment by GiovanniSalmeri** [comment]
Hello @derion1. I am not sure I understand your problem. I have made a fresh installation of Yellow and I have added the Comment extension. The result is:

+ Comment fields are not shown in the blog main page
+ Comment fields are shown at the end of each post page
+ If I add `Comment: exclude` in a post page, comment fields are not shown.

Are you using the latest version of both this extension and Yellow? If so, can you give me some details more? Thank you!

**Comment by ghost** [comment]
Hi, Giovannni. 
Well, the problem is gone now (not sure why). Anyway, the problem was on my website.com/blog page, meaning the page for the blog part of the site. On that page you can see links to blog posts, and at the bottom of the main blog page it would show the Comment section, which was weird, because why would you like to comment on the main blog page? Comments are placed on single blog posts, not the main page. Anyway, I cannot see the problem now, maybe it vanished after Blog section gets more and many pages of blog posts, as I have now. 

I guess we can close this case, but I will get back if the issue reappears.  We can mark this as resolved. Thanks.
