### ISSUE TITLE
[Error] Deprecated: Creation of dynamic property YellowComment::$comments

### ISSUE THREAD

**Issue by pftnhr** [nasendackel/yellow-comments#38]
Hi Giovanni,

I get the following error message when I am in `CoreDebugMode: 1`:

```
Deprecated: Creation of dynamic property YellowComment::$comments is deprecated in /www/htdocs/w01e3007/frittiert.es/system/extensions/comment.php on line 229
```

When I exit the DebugMode, no error message appears and the extension seems to work so far. The only bug then: I do not receive a notification e-mail.

**Comment by GiovanniSalmeri** [comment]
Thank you very much for reporting! Could you try to change line comment.php:8 like this? From:

```
    var $comment;
```

to:

```
    var $comments;
```

I suspect that it is a trivial typo...

**Comment by GiovanniSalmeri** [comment]
> The only bug then: I do not receive a notification e-mail.

As regards the notification e-mails, I have to check the extension against the new Yellow API, and I have to modify my `mailer.php` for all the Yellow extensions to use the more reliable SMTP transport. I hope that I will be able to do this in the next days...

**Comment by pftnhr** [comment]
> Thank you very much for reporting! Could you try to change line comment.php:8 like this? From:
> 
> ```
>     var $comment;
> ```
> 
> to:
> 
> ```
>     var $comments;
> ```
> 
> I suspect that it is a trivial typo...

That solved it!



> > The only bug then: I do not receive a notification e-mail.
> 
> As regards the notification e-mails, I have to check the extension against the new Yellow API, and I have to modify my `mailer.php` for all the Yellow extensions to use the more reliable SMTP transport. I hope that I will be able to do this in the next days...

A few days ago I received notifications after a test comment. It's kind of strange but not so problematic to me.
