### ISSUE TITLE
Unpublished comments show up in search results

### ISSUE THREAD

**Issue by pftnhr** [nasendackel/yellow-comments#39]
Hi Giovanni,

I just did some searching on my site and found an unpublished comment:

<img width="781" alt="Bildschirmfoto 2023-08-28 um 16 55 06" src="https://github.com/GiovanniSalmeri/yellow-comment/assets/7520987/7eadadbf-187b-4955-ae47-f34d4b18ba86">

Now I don't know if it's your extension or Yellow's search function.

**Comment by GiovanniSalmeri** [comment]
Thank you very much for the report! Perhaps the first version of YellowComment (which I took over years ago) was written when YellowSearch did'nt exist yet and I have never realised that they interact badly. The simplest solution is to exclude wholly the comments from search results. I think that this can be achieved simply by changing line comment.php:256 like this:

```
        $content = "---\nTitle: Comment\nStatus: unlisted\n---\n";
```

But in already created comment pages you should fix by hand the first lines:

```
---
Title: Comment
Status: unlisted
---
```

For the published comments to show up properly in search results, the solution is not so easy. Perhaps the whole code of YellowComment should be refactored, I will think about it!

**Comment by pftnhr** [comment]
For me, comments in the search results would be a nice-to-have but not a must. I'm fine like this, especially since no one ever comes to my site anyway. 😅

**Comment by GiovanniSalmeri** [comment]
I put this in my Todo list 😊
