### ISSUE TITLE
All comments are filed twice

### ISSUE THREAD

**Issue by pftnhr** [nasendackel/yellow-comments#40]
I tested the comment function again today and noticed that all comments are stored twice in the same location. But as already mentioned, I don't need comments at the moment, but it would be nice to be able to offer them at some point.

If you need help then, feel free to contact me.

**Comment by GiovanniSalmeri** [comment]
Thank you very much for warning me. As soon as possible (but not earlier than October) I will review the extension, I hope to correct all the glitches.

**Comment by GiovanniSalmeri** [comment]
@pftnhr After some tests I couldn't reproduce this problem (with a new installation), even if I detected some different glitches. Could you describe more exactly what do you mean by "stored twice in the same location"? Thank you!

**Comment by pftnhr** [comment]
Hi Giovanni,

it will be a while before I test it again, as I decided to use a `Comment via e-mail` link instead of full comments for my website.

**Comment by GiovanniSalmeri** [comment]
If you don't mind, I close this issue just so I don't tget confused. Please feel free to reopen it if you have any further information. Thank you very much!
