### ISSUE TITLE
fatal error when comments published 

### ISSUE THREAD

**Issue by Mao-urban** [nasendackel/yellow-comments#41]
website returns fatal error when a comment is approved for publishing

**Comment by GiovanniSalmeri** [comment]
Thank you for warning me, I will do a test with a fresh installation, if I don't understant the problem I will come back to you asking for further informations.

**Comment by Mao-urban** [comment]
> Thank you for warning me, I will do a test with a fresh installation, if I don't understant the problem I will come back to you asking for further informations.
this is error return
system/extensions/comment.php on line 139

Fatal error: Uncaught Error: Call to undefined method YellowLanguage::normaliseDate() in /home/kverse/www/kverse/system/extensions/comment.php:139 Stack trace: #0 /home/kverse/www/kverse/system/extensions/core.php(3073): YellowComment->onParseContentShortcut(Object(YellowPage), 'comment', '', 'block') #1 /home/kverse/www/kverse/system/extensions/markdown.php(3890): YellowPage->parseContentShortcut('comment', '', 'block') #2 [internal function]: YellowMarkdownParser->_doAutoLinks_shortcutBlock_callback(Array) #3 /home/kverse/www/kverse/system/extensions/markdown.php(3879): preg_replace_callback('/^\\s*\\[(\\w+)([^...', Array, '[comment]') #4 /home/kverse/www/kverse/system/extensions/markdown.php(669): YellowMarkdownParser->doAutoLinks('[comment]') #5 /home/kverse/www/kverse/system/extensions/markdown.php(3518): MarkdownParser->runSpanGamut('[comment]') #6 /home/kverse/www/kverse/system/extensions/markdown.php(613): MarkdownExtraParser->formParagraphs('B\x1A12B\n\n\n\n\n[brea...') #7 /home/kverse/www/kverse/system/extensions/markdown.php(299): MarkdownParser->runBasicBlockGamut('\nB\x1A12B\n\n\n\n\n[bre...') #8 /home/kverse/www/kverse/system/extensions/markdown.php(16): MarkdownParser->transform('>Novel Name: *[...') #9 /home/kverse/www/kverse/system/extensions/core.php(3046): YellowMarkdown->onParseContentRaw(Object(YellowPage), '>Novel Name: *[...') #10 /home/kverse/www/kverse/system/extensions/core.php(194): YellowPage->parseContent() #11 /home/kverse/www/kverse/system/extensions/core.php(141): YellowCore->sendPage('https', 'kverselibrary.c...', '/edit', '/mtlnovels/LAA/...', 'content/7-mtlno...', false, true) #12 /home/kverse/www/kverse/system/extensions/edit.php(297): YellowCore->processRequest('https', 'kverselibrary.c...', '/edit', '/mtlnovels/LAA/...', 'content/7-mtlno...', false) #13 /home/kverse/www/kverse/system/extensions/edit.php(259): YellowEdit->processRequestShow('https', 'kverselibrary.c...', '/edit', '/mtlnovels/LAA/...', 'content/7-mtlno...') #14 /home/kverse/www/kverse/system/extensions/edit.php(68): YellowEdit->processRequest('https', 'kverselibrary.c...', '/edit', '/mtlnovels/LAA/...', 'content/7-mtlno...') #15 /home/kverse/www/kverse/system/extensions/core.php(106): YellowEdit->onRequest('https', 'kverselibrary.c...', '/edit', '/mtlnovels/LAA/...', 'content/7-mtlno...') #16 /home/kverse/www/kverse/yellow.php(9): YellowCore->request() #17 {main} thrown in /home/kverse/www/kverse/system/extensions/comment.php on line 139

Datenstrom Yellow stopped with fatal error. Activate the debug mode for more information. [See troubleshooting](https://datenstrom.se/yellow/help/troubleshooting).

**Comment by GiovanniSalmeri** [comment]
Thank you for sharing. This extension used a method `language->normalisedDate` which has been recently removed from Yellow. Tomorrow I will adapt the code to the latest version, thank you for your patience!

**Comment by Mao-urban** [comment]
> Thank you for sharing. This extension used a method `language->normalisedDate` which has been recently removed from Yellow. Tomorrow I will adapt the code to the latest version, thank you for your patience!

Thank you

**Comment by GiovanniSalmeri** [comment]
I have just updated the extension, if you download and install the new version it should work. Can you confirm that all is in order?

**Comment by GiovanniSalmeri** [comment]
I hope all is in order. I close the issue, but feel free to reopen it if there are still problems.
