### ISSUE TITLE
Comments order

### ISSUE THREAD

**Issue by LeszekRzezimieszek** [nasendackel/yellow-comments#42]
Hi, Is it possible to set comments to appear in ascending or descending order? Kind regards

**Comment by GiovanniSalmeri** [comment]
Currently this option is not provided. Whether ascending or descending order is better is [much debated](https://ux.stackexchange.com/questions/18730/which-comment-sorting-order-makes-more-sense-on-blogs). Even if Yellow's philosophy is to reduce as much as possible options (less is more), if you think that this would be actually useful for your use case, I can add this possiblity (it is indeed very easy). Let me know!

**Comment by LeszekRzezimieszek** [comment]
Hmm... there is a whole discussion about it :)

Ok, in my opinion the newer comments should be at the top of the page. Unfortunately, in the default setting of this extension,  comments are sorted in reverse. I would greatly appreciate it if you add the possibility to set ascending or descending order.

**Comment by GiovanniSalmeri** [comment]
@LeszekRzezimieszek Now added the setting `CommentReverseOrder`. It changes accordingly also the position of the form (at the beginning or at the end of the comments).

I have checked some popular commenting system, and several among them allow to change dynamically the order of the comments. This is feasible, but requires some Javascript and in my opinion leaves to the reader a choice which the webmaster should do. Actually the different order encourages different ways of commenting. Oldest first suggests: read the article, then read the other comments, then add your comment if you have something different to say. Newest first suggests: read the article, then add your reaction if you feel like it, no matter whether it has been already said. Each way has its advantages and drawbacks: but are different things, which shouldn't be mixed up.

Anyway, I haven't yet read something about online commenting more insightful than the [twenty-year old article by Joel Spolsky](https://www.joelonsoftware.com/2003/03/03/building-communities-with-software/). It talks about forums, but most observations apply also to commenting systems.

**Comment by LeszekRzezimieszek** [comment]
Thank you very much! It works perfectly now. This thread can be closed.
