### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by wunderfeyd** [nasendackel/yellow-comments#7]
We'll keep the task list up to date.

Near future:
- ~~lock the comment file from read to write~~
- ~~timeout for unpublished/not approved comments~~
- ~~blacklist~~
- ~~link highlightning~~ / image loading (whitelisted origins) inside the comments (or better Markdown)
- ~~Emoticons (reuse emoji plugin) emoji plugin still lacks some settings/features~~
- ~~icons for each individual user (created by hash of the mail address like mine on github :) ) and gravatar~~
- Approve mail with website authentication (for more security)
- ~~installation and settings documentation~~

Beyond:
- threaded comments (reponses to specific comments already written)
- user mail validation
- user accounts / upload or select individual graphics
- comment count (how much has each user commented)

**Comment by ghost** [comment]
Maybe gravatar support for user icon?

**Comment by wunderfeyd** [comment]
Great idea. :)

**Comment by ghost** [comment]
I am closing the repository. Do you want to take over the code?

**Comment by wunderfeyd** [comment]
No problem. Please use your Github repository settings menu to transfer the ownership into my account.

Thank you very much for being responsive and great to your users all the time.  :+1: I hope we have the opportunity to work together in the future again on something else.

**Comment by ghost** [comment]
Thanks! Have fun with it :)

**Comment by wunderfeyd** [comment]
Thanks for your efforts. Have a great time and good luck with your personal projects. :)

**Comment by wunderfeyd** [comment]
I think this issue/task lost is too old. Closing.
