### ISSUE TITLE
User Icon

### ISSUE THREAD

**Issue by ghost** [nasendackel/yellow-comments#8]
I get this error with the new user icon:

<img style="height:3em; width:3em;" src="data:image/png;base64,&lt;br /&gt;
&lt;b&gt;Warning&lt;/b&gt;:  gzcompress() expects at most 2 parameters, 3 given in &lt;b&gt;/www/htdocs/w0080f53/nasendackel/blog/system/plugins/comments.php&lt;/b&gt; on line &lt;b&gt;378&lt;/b&gt;&lt;br /&gt;
iVBORw0KGgoAAAANSUhEUgAAAUAAAAFAAQMAAAD3XjfpAAAABlBMVEX/AM////9vM8pBAAAAAElEQVQ1rwYeAAAAAElFTkSuQmCC">

**Comment by wunderfeyd** [comment]
Thanks for reporting. Didn't see the last parameter was for PHP 5.4 only. Will upload corrected version soon.

**Comment by wunderfeyd** [comment]
Fixed in the most recent version. Also added Gravatar (enabled with `commentsIconGravatar: 1` in the settings file.

Could you check both please? I have no Gravatar. :)

**Comment by ghost** [comment]
Both works! Great!

**Comment by wunderfeyd** [comment]
No problem. Great and fast feedback by you. Keep up the good work.
